package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"ketukApps/config"
	_ "ketukApps/docs" // docs is generated by Swag CLI
	"ketukApps/internal/database"
	"ketukApps/internal/handlers"
	"ketukApps/internal/middleware"
	"ketukApps/internal/queue"
	"ketukApps/internal/scheduler"
	"ketukApps/internal/services"
	"ketukApps/internal/utils"
)

// @title KetukApps API
// @version 1.0
// @description This is the API documentation for KetukApps backend service.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@ketukapp.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /
// @schemes http https

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// Load configuration
	cfg := config.Load()

	// Set JWT secret
	utils.SetJWTSecret(cfg.JWTSecret)

	//set smpt gmail auth
	GmailSmtpAuth := utils.SetSMTPAuth(cfg.SMTPGmail.Email, cfg.SMTPGmail.Password, cfg.SMTPGmail.Host)

	// Initialize database
	if err := database.Initialize(cfg); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer database.Close()

	db := database.GetDB()

	// Initialize RabbitMQ
	if err := queue.NewRabbitMQConnection(cfg); err != nil {
		log.Fatalf("Failed to initialize RabbitMQ: %v", err)
	}
	defer queue.CloseRabbitMQ()

	// Initialize services
	userService := services.NewUserService(db)
	ticketService := services.NewTicketServiceWithEmail(db, &GmailSmtpAuth, cfg.SMTPGmail.Host, cfg.SMTPGmail.Email)
	scheduleService := services.NewScheduleService(db)
	itemsService := services.NewItemService(db)
	unblockingService := services.NewUnblockingService(db)
	googleOAuthService := services.NewGoogleOAuthService(cfg)
	auditService := services.NewAuditService(db)
	formLinkService := services.NewFormLinkService(db)

	// Start the worker with ticket service and schedule service
	go func() {
		if err := queue.SchduleWorker(cfg.Queue.Name, ticketService, scheduleService, &GmailSmtpAuth, cfg.SMTPGmail.Email); err != nil {
			log.Fatalf("Failed to start schedule worker: %v", err)
		}
	}()

	// Initialize handlers
	authHandler := handlers.NewAuthHandler(db, googleOAuthService)
	userHandler := handlers.NewUserHandler(userService)
	tickets := handlers.NewTicketHandler(ticketService)
	items := handlers.NewItemHandler(itemsService)
	unblockingHandler := handlers.NewUnblockingHandler(unblockingService)
	scheduleHandler := handlers.NewScheduleHandler(scheduleService)
	auditHandler := handlers.NewAuditHandler(auditService)
	formLinkHandler := handlers.NewFormLinkHandler(formLinkService)

	// Setup Gin router
	router := setupRouter(authHandler, userHandler, tickets, items, unblockingHandler, scheduleHandler, auditHandler, formLinkHandler)

	// Setup Scheduler

	scheduler, err := scheduler.NewScheduler(db)
	if err != nil {
		log.Fatalf("Failed to create scheduler: %v", err)
	}
	defer scheduler.Shutdown()
	// Register unblock job
	if err := scheduler.RegisterUnblockJob(); err != nil {
		log.Fatalf("Failed to register unblock job: %v", err)
	}
	scheduler.Start()

	// Start server
	address := fmt.Sprintf("%s:%s", cfg.Host, cfg.Port)
	log.Printf("🚀 Server starting on http://%s", address)
	log.Printf("📚 Swagger Documentation: http://%s/swagger/index.html", address)

	if err := router.Run(address); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}

func setupRouter(authHandler *handlers.AuthHandler, userHandler *handlers.UserHandler, ticketHandler *handlers.TicketHandler, itemHandler *handlers.ItemHandler, unblockingHandler *handlers.UnblockingHandler, scheduleHandler *handlers.ScheduleHandler, auditHandler *handlers.AuditHandler, formLinkHandler *handlers.FormLinkHandler) *gin.Engine {
	// Set Gin mode based on environment
	gin.SetMode(gin.DebugMode) // Change to gin.DebugMode for development

	// Create router with default middleware
	router := gin.New()

	// Add custom middleware
	router.Use(middleware.Logger())
	router.Use(middleware.CORS())
	router.Use(middleware.ErrorHandler())
	router.Use(gin.Recovery())

	// Health check endpoint
	router.GET("/health", handlers.HealthCheck)

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API routes group
	api := router.Group("/api")
	{
		// Auth endpoints (public)
		auth := api.Group("/auth")
		{
			auth.POST("/v1/register", authHandler.Register)
			auth.POST("/v1/login", authHandler.Login)
			auth.POST("/v1/refresh", authHandler.RefreshToken)
			auth.GET("/v1/me", middleware.AuthRequired(), authHandler.Me)

			// Google OAuth
			auth.GET("/v1/google/login", authHandler.GoogleLogin)
			auth.GET("/v1/google/callback", authHandler.GoogleCallback)
		}

		// Protected routes - require authentication
		protected := api.Group("")
		protected.Use(middleware.AuthRequired())
		{
			// Users endpoints - Admin only except GET (which can be accessed by authenticated users)
			users := protected.Group("/users")
			{
				users.GET("/v1", middleware.RequireRole("admin", "user"), userHandler.GetAllUsers)
				users.GET("/v1/:id", middleware.RequireRole("admin", "user"), userHandler.GetUserByID)
				users.POST("/v1", middleware.RequireRole("admin"), userHandler.CreateUser)
				users.PUT("/v1/:id", middleware.RequireRole("admin"), userHandler.UpdateUser)
				users.DELETE("/v1/:id", middleware.RequireRole("admin"), userHandler.DeleteUser)
			}

			// Tickets endpoints
			tickets := protected.Group("/tickets")
			{
				// All authenticated users can view and create tickets
				tickets.GET("/v1", middleware.RequireRole("admin", "user"), middleware.CheckUnblockState(), ticketHandler.GetAllTickets)
				tickets.GET("/v1/:id", middleware.RequireRole("admin", "user"), middleware.CheckUnblockState(), ticketHandler.GetTicketByID)
				tickets.GET("/v1/user/:user_id", middleware.RequireRole("admin", "user"), middleware.CheckUnblockState(), ticketHandler.GetTicketsByUserID)
				tickets.POST("/v1", middleware.RequireRole("admin", "user"), middleware.CheckUnblockState(), ticketHandler.CreateTicket)

				// Only admin can update, delete, and change status
				tickets.PUT("/v1/:id", middleware.RequireRole("admin"), middleware.CheckUnblockState(), ticketHandler.UpdateTicket)
				tickets.DELETE("/v1/:id", middleware.RequireRole("admin"), middleware.CheckUnblockState(), ticketHandler.DeleteTicket)
				tickets.PATCH("/v1/:id/status", middleware.RequireRole("admin"), middleware.CheckUnblockState(), ticketHandler.UpdateTicketStatus)
				tickets.POST("/v1/bulk-status", middleware.RequireRole("admin"), middleware.CheckUnblockState(), ticketHandler.BulkUpdateStatus)
			}

			// Items endpoints
			items := protected.Group("/items")
			{
				// Users can read, admin can do everything
				items.GET("/v1", middleware.RequireRole("admin", "user"), itemHandler.GetAllItems)
				items.GET("/v1/:id", middleware.RequireRole("admin", "user"), itemHandler.GetItemByID)
				items.GET("/v1/category/:category_id", middleware.RequireRole("admin", "user"), itemHandler.GetItemsByCategoryID)

				// Admin only
				items.POST("/v1", middleware.RequireRole("admin"), itemHandler.CreateItem)
				items.PUT("/v1/:id", middleware.RequireRole("admin"), itemHandler.UpdateItem)
				items.DELETE("/v1/:id", middleware.RequireRole("admin"), itemHandler.DeleteItem)
			}

			// Item Categories endpoints
			ItemsCategory := protected.Group("/item-categories")
			{
				// Users can read, admin can do everything
				ItemsCategory.GET("/v1", middleware.RequireRole("admin", "user"), itemHandler.GetAllItemCategories)
				ItemsCategory.GET("/v1/:id", middleware.RequireRole("admin", "user"), itemHandler.GetItemCategoryByID)

				// Admin only
				ItemsCategory.POST("/v1", middleware.RequireRole("admin"), itemHandler.CreateItemCategory)
				ItemsCategory.PUT("/v1/:id", middleware.RequireRole("admin"), itemHandler.UpdateItemCategory)
				ItemsCategory.DELETE("/v1/:id", middleware.RequireRole("admin"), itemHandler.DeleteItemCategory)
			}

			// Unblocking endpoints
			unblocking := protected.Group("/unblockings")
			{
				// All authenticated users can view and create unblocking requests
				unblocking.GET("/v1", middleware.RequireRole("admin"), unblockingHandler.GetAllUnblockings)
				unblocking.GET("/v1/:id", middleware.RequireRole("admin"), unblockingHandler.GetUnblockingByID)
				unblocking.GET("/v1/user/:user_id", middleware.RequireRole("admin"), unblockingHandler.GetUnblockingsByUserID)
				unblocking.POST("/v1", middleware.RequireRole("admin"), unblockingHandler.CreateUnblocking)
			}

			// Schedule Reguler endpoints
			scheduleReguler := protected.Group("/schedules/reguler")
			{
				// All authenticated users can view, admin can manage
				scheduleReguler.GET("/v1", middleware.RequireRole("admin", "user"), scheduleHandler.GetAllScheduleReguler)
				scheduleReguler.GET("/v1/:id", middleware.RequireRole("admin", "user"), middleware.CheckUnblockStateReverseTechnique(), scheduleHandler.GetScheduleRegulerByID)
				scheduleReguler.GET("/v1/user/:user_id", middleware.RequireRole("admin", "user"), middleware.CheckUnblockStateReverseTechnique(), scheduleHandler.GetScheduleRegulerByUserID)

				// Admin only
				scheduleReguler.POST("/v1", middleware.RequireRole("admin"), scheduleHandler.CreateScheduleReguler)
				scheduleReguler.PUT("/v1/:id", middleware.RequireRole("admin"), middleware.CheckUnblockStateReverseTechnique(), scheduleHandler.UpdateScheduleReguler)
				scheduleReguler.DELETE("/v1/:id", middleware.RequireRole("admin"), middleware.CheckUnblockStateReverseTechnique(), scheduleHandler.DeleteScheduleReguler)
			}

			// Schedule Ticket endpoints
			scheduleTicket := protected.Group("/schedules/tickets")
			{
				// All authenticated users can view, admin can manage
				scheduleTicket.GET("/v1", middleware.RequireRole("admin", "user"), scheduleHandler.GetAllScheduleTickets)
				scheduleTicket.GET("/v1/:id", middleware.RequireRole("admin", "user"), scheduleHandler.GetScheduleTicketByID)
				scheduleTicket.GET("/v1/user/:user_id", middleware.RequireRole("admin", "user"), scheduleHandler.GetScheduleTicketsByUserID)
				scheduleTicket.GET("/v1/category/:category", middleware.RequireRole("admin", "user"), scheduleHandler.GetScheduleTicketsByCategory)

				// Admin only
				scheduleTicket.POST("/v1", middleware.RequireRole("admin"), scheduleHandler.CreateScheduleTicket)
				scheduleTicket.PUT("/v1/:id", middleware.RequireRole("admin"), scheduleHandler.UpdateScheduleTicket)
				scheduleTicket.DELETE("/v1/:id", middleware.RequireRole("admin"), scheduleHandler.DeleteScheduleTicket)
			}

			// Audit endpoints
			audit := protected.Group("/audit")
			{
				// Both users and admins can view audit logs
				audit.GET("/tickets/:ticket_id/logs", middleware.RequireRole("admin", "user"), auditHandler.GetTicketEventLogs)
				audit.GET("/users/:user_id/logs", middleware.RequireRole("admin"), auditHandler.GetEventLogsByUser)
				// Admin only can view all audit logs
				audit.GET("/logs", middleware.RequireRole("admin"), auditHandler.GetAllEventLogs)
			}

			// Form Links endpoints (admin only)
			formLinks := protected.Group("/form-links")
			{
				formLinks.GET("/v1", middleware.RequireRole("admin"), formLinkHandler.GetAllFormLinks)
				formLinks.GET("/v1/:id", middleware.RequireRole("admin"), formLinkHandler.GetFormLinkByID)
				formLinks.POST("/v1", middleware.RequireRole("admin"), formLinkHandler.CreateFormLink)
				formLinks.PUT("/v1/:id", middleware.RequireRole("admin"), formLinkHandler.UpdateFormLink)
				formLinks.DELETE("/v1/:id", middleware.RequireRole("admin"), formLinkHandler.DeleteFormLink)
				formLinks.PATCH("/v1/:id/deactivate", middleware.RequireRole("admin"), formLinkHandler.DeactivateFormLink)
				formLinks.POST("/v1/:id/clone", middleware.RequireRole("admin"), formLinkHandler.CloneFormLink)
				formLinks.GET("/v1/:id/submissions", middleware.RequireRole("admin"), formLinkHandler.GetSubmissions)
			}
		}

		// Public endpoints (no authentication required)
		public := api.Group("/public")
		{
			public.GET("/form/:code", formLinkHandler.GetPublicForm)
			public.POST("/form/:code/submit", formLinkHandler.SubmitPublicForm)
		}
	}

	return router
}
