package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"ketukApps/config"
	_ "ketukApps/docs" // docs is generated by Swag CLI
	"ketukApps/internal/database"
	"ketukApps/internal/handlers"
	"ketukApps/internal/middleware"
	"ketukApps/internal/queue"
	"ketukApps/internal/services"
	"ketukApps/internal/utils"
)

// @title KetukApps API
// @version 1.0
// @description This is the API documentation for KetukApps backend service.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@ketukapp.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /
// @schemes http https

func main() {
	// Load configuration
	cfg := config.Load()

	// Set JWT secret
	utils.SetJWTSecret(cfg.JWTSecret)

	// Initialize database
	if err := database.Initialize(cfg); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer database.Close()

	db := database.GetDB()

	// Initialize RabbitMQ
	if err := queue.NewRabbitMQConnection(cfg); err != nil {
		log.Fatalf("Failed to initialize RabbitMQ: %v", err)
	}
	defer queue.CloseRabbitMQ()

	// Initialize services
	userService := services.NewUserService(db)
	ticketService := services.NewTicketService(db)
	scheduleService := services.NewScheduleService(db)
	itemsService := services.NewItemService(db)
	googleOAuthService := services.NewGoogleOAuthService(cfg)

	// Start the worker with ticket service and schedule service
	go func() {
		if err := queue.SchduleWorker(cfg.Queue.Name, ticketService, scheduleService); err != nil {
			log.Fatalf("Failed to start schedule worker: %v", err)
		}
	}()

	// Initialize handlers
	authHandler := handlers.NewAuthHandler(db, googleOAuthService)
	userHandler := handlers.NewUserHandler(userService)
	tickets := handlers.NewTicketHandler(ticketService)
	items := handlers.NewItemHandler(itemsService)

	// Setup Gin router
	router := setupRouter(authHandler, userHandler, tickets, items)

	// Start server
	address := fmt.Sprintf("%s:%s", cfg.Host, cfg.Port)
	log.Printf("🚀 Server starting on http://%s", address)
	log.Printf("📚 Swagger Documentation: http://%s/swagger/index.html", address)

	if err := router.Run(address); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}

func setupRouter(authHandler *handlers.AuthHandler, userHandler *handlers.UserHandler, ticketHandler *handlers.TicketHandler, itemHandler *handlers.ItemHandler) *gin.Engine {
	// Set Gin mode based on environment
	gin.SetMode(gin.DebugMode) // Change to gin.DebugMode for development

	// Create router with default middleware
	router := gin.New()

	// Add custom middleware
	router.Use(middleware.Logger())
	router.Use(middleware.CORS())
	router.Use(middleware.ErrorHandler())
	router.Use(gin.Recovery())

	// Health check endpoint
	router.GET("/health", handlers.HealthCheck)

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API routes group
	api := router.Group("/api")
	{
		// Auth endpoints (public)
		auth := api.Group("/auth")
		{
			auth.POST("/v1/register", authHandler.Register)
			auth.POST("/v1/login", authHandler.Login)
			auth.POST("/v1/refresh", authHandler.RefreshToken)
			auth.GET("/v1/me", middleware.AuthRequired(), authHandler.Me)

			// Google OAuth
			auth.GET("/v1/google/login", authHandler.GoogleLogin)
			auth.GET("/v1/google/callback", authHandler.GoogleCallback)
		}

		// Protected routes - require authentication
		protected := api.Group("")
		protected.Use(middleware.AuthRequired())
		{
			// Users endpoints - Admin only except GET (which can be accessed by authenticated users)
			users := protected.Group("/users")
			{
				users.GET("/v1", middleware.RequireRole("admin", "user"), userHandler.GetAllUsers)
				users.GET("/v1/:id", middleware.RequireRole("admin", "user"), userHandler.GetUserByID)
				users.POST("/v1", middleware.RequireRole("admin"), userHandler.CreateUser)
				users.PUT("/v1/:id", middleware.RequireRole("admin"), userHandler.UpdateUser)
				users.DELETE("/v1/:id", middleware.RequireRole("admin"), userHandler.DeleteUser)
			}

			// Tickets endpoints
			tickets := protected.Group("/tickets")
			{
				// All authenticated users can view and create tickets
				tickets.GET("/v1", middleware.RequireRole("admin", "user"), ticketHandler.GetAllTickets)
				tickets.GET("/v1/:id", middleware.RequireRole("admin", "user"), ticketHandler.GetTicketByID)
				tickets.POST("/v1", middleware.RequireRole("admin", "user"), ticketHandler.CreateTicket)

				// Only admin can update, delete, and change status
				tickets.PUT("/v1/:id", middleware.RequireRole("admin"), ticketHandler.UpdateTicket)
				tickets.DELETE("/v1/:id", middleware.RequireRole("admin"), ticketHandler.DeleteTicket)
				tickets.PATCH("/v1/:id/status", middleware.RequireRole("admin"), ticketHandler.UpdateTicketStatus)
				tickets.POST("/v1/bulk-status", middleware.RequireRole("admin"), ticketHandler.BulkUpdateStatus)
			}

			// Items endpoints
			items := protected.Group("/items")
			{
				// Users can read, admin can do everything
				items.GET("/v1", middleware.RequireRole("admin", "user"), itemHandler.GetAllItems)
				items.GET("/v1/:id", middleware.RequireRole("admin", "user"), itemHandler.GetItemByID)
				items.GET("/v1/category/:category_id", middleware.RequireRole("admin", "user"), itemHandler.GetItemsByCategoryID)

				// Admin only
				items.POST("/v1", middleware.RequireRole("admin"), itemHandler.CreateItem)
				items.PUT("/v1/:id", middleware.RequireRole("admin"), itemHandler.UpdateItem)
				items.DELETE("/v1/:id", middleware.RequireRole("admin"), itemHandler.DeleteItem)
			}

			// Item Categories endpoints
			ItemsCategory := protected.Group("/item-categories")
			{
				// Users can read, admin can do everything
				ItemsCategory.GET("/v1", middleware.RequireRole("admin", "user"), itemHandler.GetAllItemCategories)
				ItemsCategory.GET("/v1/:id", middleware.RequireRole("admin", "user"), itemHandler.GetItemCategoryByID)

				// Admin only
				ItemsCategory.POST("/v1", middleware.RequireRole("admin"), itemHandler.CreateItemCategory)
				ItemsCategory.PUT("/v1/:id", middleware.RequireRole("admin"), itemHandler.UpdateItemCategory)
				ItemsCategory.DELETE("/v1/:id", middleware.RequireRole("admin"), itemHandler.DeleteItemCategory)
			}
		}
	}

	return router
}
